service: serverless-react-workshop

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage}
    environment:
        PAGE_TABLE: ${self:service}-pages-${self:provider.stage}

functions:
    graphql:
        handler: dist/graphql.handler
        events:
            - http:
                  path: graphql
                  method: GET
                  cors: true
            - http:
                  path: graphql
                  method: POST
                  cors: true

resources:
    PagesTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: pageId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: pageId
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName: ${self:provider.environment.PAGE_TABLE}
